// History Eraser for Google Chrome - HOTCLEANER.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
chrome.runtime.onStartup.addListener(function(){});
(function(){function p(){chrome.runtime.onMessage.addListener(z);c.p29&&q(1);c.p30&&r(1);c.p32&&t(1);chrome.browserAction.onClicked.addListener(function(){l("cleaner.html",!0,770,500)});setTimeout(u,1307)}function A(){if(3==c.nv)v(1);else if("4.7.1"!==c.ver){var a=g;c.nv=Math.floor(Math.random()*(a+10368E5-a+1))+a;c.ver="4.7.1";h();setTimeout(u,2177)}else 0<c.nv&&c.nv<g?v():c.p31&&6048E5<g-c.lr&&l("cleaner.html",!0,770,500)}function h(){localStorage.setItem("opt",JSON.stringify(c))}function v(a){c.nv=
0;h();a?k("https://www.hotcleaner.com/clickclean/install-eraser.html",!1):k("https://www.hotcleaner.com/history-eraser-chrome-extension-app.html#ehnehba",!0);ga({ea:a?"install":"update"})}function B(a,b){if(7578==a.menuItemId)chrome.history.deleteUrl({url:b.url},function(){C(b.url,function(){chrome.tabs.executeScript(b.id,{file:"safe.js"})})});else if(7579==a.menuItemId){var f=a.linkUrl,d=f.indexOf("&url="),e;0<d&&(e=f.indexOf("&",d+5),f=decodeURIComponent(f.slice(d+5,e)));chrome.tabs.create({url:f})}else 7580==
a.menuItemId&&chrome.tabs.create({url:"https://encrypted.google.com/search?q="+encodeURIComponent(a.selectionText)+"&tbo=1"})}function q(a){chrome.contextMenus.removeAll();a&&(a=chrome.i18n.getMessage("ctxMenu").split(";"),chrome.contextMenus.create({id:"7578",title:a[0],contexts:["page"]}),chrome.contextMenus.create({id:"7579",title:a[1],contexts:["link"]}),chrome.contextMenus.create({id:"7580",title:a[2],contexts:["selection"]}),chrome.contextMenus.onClicked.addListener(B))}function r(a){chrome.tabs.onCreated[a?
"addListener":"removeListener"](w);chrome.tabs.onUpdated[a?"addListener":"removeListener"](w)}function x(a){chrome.browserAction.setTitle({title:0<a?"Visited Pages: "+a+"\nLaunch History Eraser":"\nLaunch History Eraser"});chrome.browserAction.setBadgeBackgroundColor({color:50<a?[255,0,0,255]:[0,162,241,255]});chrome.browserAction.setBadgeText({text:0<a?99<a?"99+":a.toString():""})}function m(){chrome.history.search({text:""},function(a){a&&-1<a.length&&x(a.length)})}function t(a){chrome.history.onVisited[a?
"addListener":"removeListener"](m);chrome.history.onVisitRemoved[a?"addListener":"removeListener"](m);a?m():x(0)}function C(a,b){function f(){e++;e<d.length?chrome.cookies.remove({url:a,name:d[e].name},f):b()}var d,e=-1;chrome.cookies.getAll({url:a},function(a){d=a;f()})}function w(a,b,f){a=f?f:a;b=a.url;0==b.indexOf(y)&&7<b.indexOf("/history/")&&chrome.tabs.update(a.id,{url:"chrome-search://local-ntp/local-ntp.html"})}function D(a,b){E(function(f){k(f?a:b)})}function k(a,b){function f(a){chrome.windows.update(a.windowId,
{focused:!0})}chrome.tabs.query({url:a},function(d){if(d&&d.length)chrome.tabs.update(d[0].id,{active:!0},f);else if(b)try{chrome.windows.create({url:a,focused:!0,incognito:!0,state:"maximized"},function(){chrome.runtime.lastError&&chrome.tabs.create({url:a,active:!0},f)})}catch(e){chrome.tabs.create({url:a,active:!0},f)}else chrome.tabs.create({url:a,active:!0},f)})}function l(a,b,f,d){a=b?chrome.runtime.getURL(a):a;chrome.tabs.query({url:a},function(e){if(e&&0<e.length)chrome.windows.update(e[0].windowId,
{focused:!0});else{var b=window.devicePixelRatio||1;e=screen.width;var c=screen.height-70,g=parseInt(d*b),b=parseInt(f*b),h=parseInt((e-b)/2),k=parseInt((c-g)/2);b>e&&(b=e,h=0);g>c&&(g=c,k=0);0>h&&(h=0);0>k&&(k=0);chrome.windows.create({type:"popup",focused:!0,url:a,top:k,left:h,width:b,height:g})}})}function z(a,b,f){try{a=JSON.parse(a)}catch(e){return}var d=a.id;0==d?l(a.url,a.local,a.w,a.h):1==d?(d=0,c.p31&&(6048E5<g-c.lr&&(d=1),c.lr=g,h()),f({v:c,u:b.tab.url,t:g,n:d})):5==d?n("GET",a.v,null,"blob",
function(b){if(a.v1){var d=new FileReader;d.onload=function(a){f(a.target.result)};d.readAsDataURL(b)}else{window.URL=window.URL||window.webkitURL;var c=window.URL.createObjectURL(b);f(c);setTimeout(function(){window.URL.revokeObjectURL(c)},1E3)}}):7==d?(c.p29!=a.v.p29?q(a.v.p29):c.p30!=a.v.p30?r(a.v.p30):c.p32!=a.v.p32&&t(a.v.p32),c=a.v,h()):8==d?D(a.v,a.v3):9==d?k(a.v,a.i):10==d?chrome.history.deleteUrl(a.v,f):11==d?chrome.history.deleteRange(a.v,f):12==d?chrome.history.search(a.v,f):13==d?chrome.history.getVisits(a.v,
f):14==d&&chrome.tabs.update(b.tab.id,{url:y+"newtab"},function(){chrome.history.deleteUrl(a.v)});return!0}function E(a){var b=new Image;b.onload=function(){a(1)};b.onerror=function(){a()};b.onabort=function(){a()};b.src="https://www.hotcleaner.com/img/2h.gif?t="+(new Date).getTime()}function u(){n("GET","manifest.json",null,"text",function(a){if(a){try{a=JSON.parse(a)}catch(b){return}n("GET",a.update_url+"?x=id%3Dgjieilkfnnjoihjjonajndjldjoagffm%26v%3D"+a.version+"%26uc",null,"text",function(a){})}})}
function n(a,b,c,d,e){var g=new XMLHttpRequest;g.open(a,b,!0);d&&(g.responseType=d);g.onload=function(a){200==this.status?e(this.response):e(null)};g.onerror=function(){e(null)};g.onabort=function(){e(null)};g.send(c)}function F(a){a=parseInt(localStorage[a]);return isNaN(a)?null:a}var g=Date.now(),y=/Comodo/.test(navigator.appVersion)?"dragon://":"chrome://",c;try{chrome.runtime.setUninstallURL("https://www.hotcleaner.com/security-and-privacy-software-feedback.html#ehuehba")}catch(a){}(function(){var a=
{ver:"4.7.1",lr:g,nv:3,timeType:10,time:0,dev:0,p0:0,p1:1,p2:1,p3:1,p4:0,p5:0,p6:1,p7:0,p8:1,p9:1,p10:1,p11:1,p12:1,p13:0,p14:0,p15:0,p16:0,p17:0,p18:0,p19:0,p20:0,p21:0,p22:0,p23:0,p24:0,p25:0,p26:0,p27:0,p28:1,p29:0,p30:0,p31:1,p32:1},b,f=Object,d;try{d=JSON.parse(localStorage.opt)}catch(k){d=null}c=null===d||d.constructor!==f?null:d;if(null===c||void 0===c.ver)c=a,b=!0;else{for(var e in c)e in a?typeof c[e]!==typeof a[e]&&(c[e]=a[e],b=!0):(delete c[e],b=!0);for(e in a)e in c||(c[e]=a[e],b=!0)}b&&
h()})();document.cookie&&-1<document.cookie.indexOf("s=7")?(g=F("st")||g,p()):(document.cookie="s=7; expires=0; path=/",localStorage.st=g,p(),A())})();
