// History Eraser for Google Chrome - HOTCLEANER.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
(function(){function n(){chrome.runtime.sendMessage(JSON.stringify({id:7,v:f}))}function N(a){O(a.u);f=a.v;w=a.t;p();var b,c,d;document.title=chrome.i18n.getMessage("m2");P();b=chrome.i18n.getMessage("cleaner2").split(";");d=document.getElementsByClassName("section");for(var e=0;4>e;e++)d[e].childNodes[0].textContent=b[e];d=document.getElementsByClassName("subtitle");for(e=0;3>e;e++)d[e].textContent=b[e+4];d=g("timeType");b=chrome.i18n.getMessage("cleaner3").split(";");g("timeLabel").textContent=
b[0];for(e=1;12>e;e++)c=document.createElement("option"),c.textContent=b[e],d.appendChild(c);d.selectedIndex=f.timeType;d.addEventListener("change",x,!1);C();b=chrome.i18n.getMessage("cleaner4").split(";");c=chrome.i18n.getMessage("cleaner5").split(";");for(e=0;33>e;e++){d=g("p"+e);f[d.id]&&d.setAttribute("on",!0);d.addEventListener("click",Q,!1);d=d.nextElementSibling;"optMore"==d.className&&(d.title=c[0],d.addEventListener("click",R,!1),d=d.nextElementSibling);if("optRun"==d.className||"optDel"==
d.className)d.title=0==e?c[1]:25==e?c[2]:26==e?c[3]:27==e?c[4]:28==e?c[5]:b[e],d.addEventListener("click",S,!1),d=d.nextElementSibling;d.textContent=d.title=b[e]}document.body.addEventListener("mousedown",function(a){"select"!=a.target.localName&&"input"!=a.target.localName&&a.preventDefault()},!1);b=document.getElementsByTagName("label");e=0;for(d=b.length;e<d;e++)b[e].addEventListener("mouseup",function(a){this.control&&setTimeout(function(){a.target.control.blur()},100)},!1);T();document.body.style.display=
"block";d=g("timeType");d.style.width=D(d.value)+40+"px";a.n&&l("m3",function(){y("https://www.hotcleaner.com/clear-browsing-history.html",chrome.runtime.getURL("history.html"))},0,0,"b2",0,"rgba(255,255,255,.75)")}function T(){chrome.tabs.getCurrent(function(a){var b=chrome.runtime.getURL("cleaner.html");chrome.tabs.query({url:b},function(b){for(var d=0,e=b.length;d<e;d++)b[d].id!=a.id&&chrome.tabs.remove(b[d].id);chrome.windows.getCurrent({},function(b){var c=window.devicePixelRatio||1,d=screen.width,
e=screen.height-70,f=parseInt(500*c),c=parseInt(770*c),g=parseInt((d-c)/2),h=parseInt((e-f)/2);c>d&&(c=d,g=0,document.body.style.zoom=window.innerWidth/850);f>e&&(f=e,h=0);0>g&&(g=0);0>h&&(h=0);"normal"==b.type?chrome.windows.create({type:"popup",focused:!0,tabId:a.id,top:h,left:g,width:c,height:f}):chrome.windows.update(b.id,{state:"normal",width:c,height:f})})})})}function S(a){a=this.parentElement.firstElementChild.id;"p5"!=a||f[a]?"p20"!=a||f[a]?z(a):l("m20b",z,q,a):l("m5b",z,q,a)}function z(a){function b(){d.className=
"ghk";m(!1,!1);(28==a||f.p28)&&E();k(0==a||25==a||28==a?"m8":"m7",500);setTimeout(function(){d.className="chk"},500)}k();m(!0,!0);var c=F(),d=g(a);a=a.slice(1);27==a?G():26==a&&H();d.className="wipe";28==a?b():I(a,c,b)}function U(){function a(a){for(var b,c=0,d=r.length;c<d;c++)b=g("p"+r[c]),b.hasAttribute("on")&&(b.className=a)}function b(){f.p28&&E();k("m7",1E3);setTimeout(function(){a("chk");m(!1,0);f.p26?H():f.p27&&G()},1E3)}function c(){setTimeout(function(){g("p"+r[v]).className="ghk";d()},
10)}function d(){v++;if(v<r.length){var a=r[v];f["p"+a]?I(a,e,c):d()}else b()}m(!0,!0);k();var e=F(),v=-1,r;r=f.dev?[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]:[0,1,2,3,4,5,6,7,8,9,10,11,12,25];a("wipe");d()}function I(a,b,c){var d=chrome.browsingData,e={since:b};13>a?0==a?J(0,c):1==a?d.removeHistory(e,c):2==a?d.removeDownloads(e,c):3==a?d.removeCache(e,c):4==a?d.remove(e,{serverBoundCertificates:!0},function(){d.removeCookies(e,c)}):5==a?d.removePasswords(e,c):6==a?d.removeFormData(e,
c):7==a?d.removeLocalStorage(e,c):8==a?d.removeWebSQL(e,c):9==a?d.removeIndexedDB(e,c):10==a?d.removeFileSystems(e,c):11==a?d.removeAppcache(e,c):12==a&&d.removePluginData(e,c):19>a?(e.originTypes={unprotectedWeb:!1,protectedWeb:!0,extension:!1},13==a?d.removeCookies(e,c):14==a?d.removeLocalStorage(e,c):15==a?d.removeWebSQL(e,c):16==a?d.removeIndexedDB(e,c):17==a?d.removeFileSystems(e,c):18==a&&d.removeAppcache(e,c)):25>a?(e.originTypes={unprotectedWeb:!1,protectedWeb:!1,extension:!0},19==a?d.removeCookies(e,
function(){document.cookie="s=7; expires=0; path=/";c()}):20==a?d.removeLocalStorage(e,function(){localStorage.st=w;localStorage.setItem("opt",JSON.stringify(f));c()}):21==a?d.removeWebSQL(e,c):22==a?d.removeIndexedDB(e,c):23==a?d.removeFileSystems(e,c):24==a&&d.removeAppcache(e,c)):25==a?J(1,c):c()}function J(a,b){chrome.tabs.getCurrent(function(c){chrome.tabs.query(a?{active:!0}:{},function(d){var e=0;d.forEach(function(b,d){c.id==b.id?0==d&&e++:a?chrome.tabs.reload(b.id):d>e?chrome.tabs.remove(b.id):
chrome.tabs.update(b.id,{url:"chrome-search://local-ntp/local-ntp.html"})});b&&setTimeout(b,500)})})}function H(){chrome.windows.getAll(function(a){for(var b=0;b<a.length;++b)chrome.windows.remove(a[b].id)})}function G(){chrome.tabs.getCurrent(function(a){chrome.tabs.remove(a.id)})}function R(a){a=parseInt(this.previousElementSibling.id.slice(1));var b=[0,4,7,8,10,13,14,15,17,19,20,21,23,25],c=/Comodo/.test(navigator.appVersion)?"dragon://":"chrome://",d=770,e=500;1==a?y("https://www.hotcleaner.com/clear-browsing-history.html",
chrome.runtime.getURL("history.html")):(0==a||25==a?c+="discards/":2==a?c+="downloads/":3==a?(c+="cache/",d=1200,e=800):-1<b.indexOf(a)?(c+="settings/cookies",d=850,e=800):5==a?(c+="settings/passwords",e=600):6==a?(c+="settings/autofill",e=800):9==a||16==a||22==a?c+="indexeddb-internals":11==a||18==a||24==a?c+="appcache-internals":12==a?c+="plugins":26==a&&(c+="version",d=850,e=800),K(c,!1,d,e))}function D(a){var b=g("textMetrics");b.textContent=a;return b.offsetWidth}function V(a){f.time=a;n()}function x(){var a=
g("timeType");f.timeType=a.selectedIndex;a.style.width=D(a.value)+40+"px";C();n()}function C(){var a=g("time");if(9==f.timeType)a.firstElementChild.hasAttribute("data-time")||calInit(a.firstElementChild,f.time,1,V),a.style.display="",g("timeType").style.width="1px";else if(a.style.display="none",a=g("cal"))a.style.display="none"}function F(){var a=f.timeType;return 10==a?0:0==a?w:9==a?f.time:Date.now()-36E5*[0,1,2,4,8,10,12,24,168][a]}function Q(a){a=this.id;"p5"!=a||f[a]?"p20"!=a||f[a]?A(a):l("m20a",
A,q,a):l("m5a",A,q,a)}function A(a){var b=g(a);b.hasAttribute("on")?(b.removeAttribute("on"),f[a]=0):(b.setAttribute("on",!0),f[a]=1);n()}function m(a,b,c){var d=g("shade"),e=g("clear");e.disabled=g("reset0").disabled=g("reset1").disabled=g("reset2").disabled=g("dev").disabled=a;d.style.backgroundColor=c?c:"";d.style.height=a?g("tab").scrollHeight+"px":"";b?e.setAttribute("on",!0):e.removeAttribute("on")}function k(a,b){var c=g("msg");a?(c.textContent=chrome.i18n.getMessage(a)+"!",c.style.top="48px",
c.t&&(clearTimeout(c.t),c.t=null),c.t=setTimeout(k,b)):c.style.top=""}function l(a,b,c,d,e,f,h){function k(){q();b(d)}function l(){q();c(d)}function q(){u.style.display="";window.removeEventListener("resize",n,!1);b&&p.removeEventListener("click",k,!1);c&&t.removeEventListener("click",l,!1);m(!1)}function n(){u.style.top=(document.body.offsetHeight-u.offsetHeight)/2+"px"}m(!0,!1,h?h:"rgba(0,0,0,.3)");var u=g("alert");h=u.firstElementChild.nextElementSibling;var t=h.nextElementSibling.firstElementChild,
p=t.nextElementSibling;h.textContent=chrome.i18n.getMessage(a);p.textContent=chrome.i18n.getMessage(e?e:"b0");t.textContent=chrome.i18n.getMessage(f?f:"b1");t.style.display=c?"inline-block":"none";u.style.display="block";c&&(t.addEventListener("click",l,!1),t.focus());b&&(p.addEventListener("click",k,!1),p.focus());n();window.addEventListener("resize",n,!1)}function h(a){var b=this.id;a=encodeURIComponent("https://www.hotcleaner.com/");var c="about:blank";"ptest"==b||"support"==b||"help"==b||"ssl"==
b||"logo"==b?W(function(a){"ptest"==b?c=a?"https://www.hotcleaner.com/clickclean-app.html#ehvehba":"https://myaccount.google.com/intro/privacycheckup/1":"support"==b?c=a?"https://www.hotcleaner.com/security-and-privacy-software-feedback.html#ehvehba":"https://www.facebook.com/clickclean":"help"==b?c=a?"https://www.hotcleaner.com/history-eraser-chrome-extension-app.html#ehvehba":"https://www.facebook.com/clickclean":"ssl"==b?c=a?"https://www.hotcleaner.com/secure_search.html":"https://support.google.com/websearch/answer/173733":
"logo"==b&&(c=a?"https://www.hotcleaner.com/#ehvehba":"https://chrome.google.com/webstore/detail/gjieilkfnnjoihjjonajndjldjoagffm");L(c,a?!0:!1)}):("rate"==b?c="https://chrome.google.com/webstore/detail/gjieilkfnnjoihjjonajndjldjoagffm/reviews":"share"==b?(b=this.sid,0==b?c="https://youtube.com/subscription_center?add_user=YTMoo":1==b?c="https://www.facebook.com/clickclean":2==b?c="https://plus.google.com/share?url="+a:3==b?c="https://twitter.com/home?status=Sometimes+-+history+needs+a+push...%3A+"+
a+"+via+%40clickclean":4==b?c="https://twitter.com/intent/user?screen_name=clickclean":5==b?c="https://mail.google.com/mail/?view=cm&fs=1&tf=1&source=mailto&body=Hi,%0a%0aI have just found great app %22History Eraser%22: %0a"+a+"%0a%0aEnjoy!&su=Sometimes - history needs a push...":6==b&&(c="https://www.pinterest.com/clickclean")):"ctrb"==b?c=chrome.runtime.getURL("ctrba.html"):"ghist"==b?c="https://history.google.com/history/settings?st=tr":"sync"==b?c="https://www.google.com/settings/chrome/sync":
"skey"==b&&(c="chrome://extensions/configureCommands"),"skey"==b?K(c,!1,770,600):L(c,!1))}function P(){function a(a,b,c,d,f){a=g(a);b&&("web"==a.className?a.firstElementChild.textContent=b:a.textContent=b);c&&(a.title=c);-1<f&&(a.sid=f,a.style.backgroundImage="url(img/s"+f+".png)");d&&a.addEventListener("click",d,!1)}var b=chrome.i18n.getMessage("cleaner1").split(";"),c=chrome.i18n.getMessage("share").split(";"),d=new Uint8Array(1);crypto.getRandomValues(d);d=d[0]%7;a("logo","v"+f.ver,0,h);a("ptest",
b[18],0,h);a("rate",b[0],b[1],h);a("share",0,c[d],h,d);a("ctrb",0,b[2],h);a("clear",b[3],0,U);a("hist",b[4],b[5],function(){y("https://www.hotcleaner.com/clear-browsing-history.html",chrome.runtime.getURL("history.html"))});a("support",b[6],0,h);a("help",b[7],0,h);a("reset0",b[8],b[13],B);a("reset1",b[9],b[13],B);a("reset2",b[10],b[13],B);a("dev",b[11],b[12],function(){f.dev?(f.dev=0,n(),p()):l("m4",function(){f.dev=1;n();p()},q)});a("export",b[14],0,X);a("import",b[15],0,Y);a("ghist",b[16],b[16],
h);a("sync",b[17],b[17],h);a("ssl",b[19],b[19],h);a("skey",b[20],b[20],h)}function p(){for(var a=g("dev"),b=document.getElementsByClassName("dev"),c=f.dev?"":"none",d=0;d<b.length;++d)b[d].style.display=c;f.dev?a.setAttribute("on",!0):a.removeAttribute("on")}function B(a){a=parseInt(this.id.slice(5));2!=a||f.p5?M(a):l("m5a",function(){M(2)},q)}function M(a){var b;0==a?b=[10,0,1,1,1,0,0,0,0,0,0,0,0,0,0]:1==a?b=[10,0,1,1,1,0,0,1,0,1,1,1,1,1,1]:2==a&&(b=[10,0,1,1,1,1,1,1,1,1,1,1,1,1,1]);f.timeType=b[0];
f.time=b[1];f.p1=b[2];f.p2=b[3];f.p3=b[4];f.p4=b[5];f.p5=b[6];f.p6=b[7];f.p7=b[8];f.p8=b[9];f.p9=b[10];f.p10=b[11];f.p11=b[12];f.p12=b[13];g("timeType").selectedIndex=f.timeType;x();for(b=1;14>b;b++)a=g("p"+b),f[a.id]?a.setAttribute("on",!0):a.removeAttribute("on");f.p31=1;f.p32=1;g("p31").setAttribute("on",!0);g("p32").setAttribute("on",!0)}function E(a){(new Audio("erased.ogg")).play();a&&setTimeout(a,400)}function O(a){a.indexOf(0==chrome.runtime.getURL(""))||0==a.indexOf("https://www.hotcleaner.com/")||
0==a.indexOf("http://www.hotcleaner.com/")||(document.location.replace="about:blank")}function y(a,b){m(1,0);k("m8",1500);chrome.runtime.sendMessage('{"id":8,"v":"'+a+'","v3":"'+b+'"}');m(0,0)}function L(a,b){chrome.runtime.sendMessage('{"id":9,"v":"'+a+'","i":'+(b?1:0)+"}")}function K(a,b,c,d){chrome.runtime.sendMessage('{"id":0,"url":"'+a+'", "local":'+b+', "w":'+c+', "h":'+d+"}")}function X(){var a,b=JSON.stringify(f);Blob?a=new Blob([b],{type:"application/json;charset=UTF-8"}):BlobBuilder&&(a=
new BlobBuilder,a.append(b),a=a.getBlob("application/json;charset=UTF-8"));Z(a,"HistoryEraser-v"+f.ver+"-Options.json")}function Y(){aa(1E5,function(a){try{a=JSON.parse(a)}catch(e){k("m12",1E3);return}var b=f.ver,c=f.nv,d;for(d in a)void 0!=f[d]&&(f[d]=a[d]);a.h0&&(f.p30=a.h0);f.ver=b;f.nv=c;g("timeType").selectedIndex=f.timeType;x();for(a=0;33>a;a++)el=g("p"+a),f[el.id]?el.setAttribute("on",!0):el.removeAttribute("on");p();k("m8",1E3)})}function aa(a,b){var c=g("openAs");c&&document.body.removeChild(c);
c=document.createElement("input");c.id="openAs";c.style.display="none";c.type="file";document.body.appendChild(c);c.addEventListener("change",function(c){if((c=c.target.files)&&1==c.length&&c[0].size<a){var e=new FileReader;e.onload=function(a){b(a.target.result)};e.readAsText(c[0])}else k("m12",1E3)},!1);c.click()}function Z(a,b){m(1,0);var c=document.createElement("a"),d=window.URL||window.webkitURL;c.href=d.createObjectURL(a);c.setAttribute("download",b);c.click();setTimeout(function(){d.revokeObjectURL(c.href);
m(0,0)},2E3)}function W(a){var b=new Image;b.onload=function(){a(1)};b.onerror=function(){a()};b.onabort=function(){a()};b.src="https://www.hotcleaner.com/img/2h.gif?t="+(new Date).getTime()}function g(a){return document.getElementById(a)}function q(){}var f,w;window.addEventListener("load",function(){chrome.runtime.sendMessage('{"id":1}',N)},!1)})();
