// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
chrome.runtime.onStartup.addListener(function(){});
(function(){function m(){chrome.runtime.onMessage.addListener(L);b.p26&&chrome.windows.onRemoved.addListener(M);b.p29&&B(1);b.p30&&C(1);b.p32&&D(1);chrome.browserAction.onClicked.addListener(function(){t("uMHZ.html",!0,770,500)})}function u(a){if(3==b.nv)E(1);else if("8.9.7"!==b.ver){var c=g;b.nv=Math.floor(Math.random()*(c+14688E5-c+1))+c;b.ver="8.9.7";h();setTimeout(v,1912)}else 0<b.nv&&b.nv<g&&E();a?F(a,1,function(){}):b.p31&&6048E5<g-b.lr&&t("uMHZ.html",!0,770,500)}function h(){for(var a=
JSON.stringify(b),c="",d=[3,0,0,-3],e,f=0,l=a.length;f<l;f++)e=d[f%4],c=f+e<l?c+a.charCodeAt(f+e).toString(16):c+a.charCodeAt(f).toString(16);window.localStorage.setItem("opt",c)}function E(a){b.nv=0;h();G(function(b){b&&w(a?"https://www.hotcleaner.com/clickclean/install-clickclean.html":"https://www.hotcleaner.com/clickclean_chrome.html#chnijha",a?!1:!0);N({ea:a?"install":"update"})});setTimeout(v,1991)}function M(a){a==x?x=-9:chrome.windows.getAll({},function(a){a&&0==a.length&&setTimeout(H,500)})}
function H(){chrome.windows.create({url:"r.html",type:"popup",top:20,left:screen.width-340,width:300,height:48},function(a){x=a.id})}function O(a,b){if(7978==a.menuItemId)chrome.history.deleteUrl({url:b.url},function(){P(b.url,function(){chrome.tabs.executeScript(b.id,{file:"js/ByWi.js"})})});else if(7979==a.menuItemId){var d=a.linkUrl,c=d.indexOf("&url="),f;0<c&&(f=d.indexOf("&",c+5),d=decodeURIComponent(d.slice(c+5,f)));chrome.tabs.create({url:d})}else 7980==a.menuItemId&&chrome.tabs.create({url:"https://encrypted.google.com/search?q="+
encodeURIComponent(a.selectionText)+"&tbo=1"})}function B(a){chrome.contextMenus.removeAll();a&&(a=chrome.i18n.getMessage("ctxMenu").split(";"),chrome.contextMenus.create({id:"7978",title:a[0],contexts:["page"]}),chrome.contextMenus.create({id:"7979",title:a[1],contexts:["link"]}),chrome.contextMenus.create({id:"7980",title:a[2],contexts:["selection"]}),chrome.contextMenus.onClicked.addListener(O))}function C(a){chrome.tabs.onCreated[a?"addListener":"removeListener"](I);chrome.tabs.onUpdated[a?"addListener":
"removeListener"](I)}function J(a){chrome.browserAction.setTitle({title:0<a?"Visited Pages: "+a+"\nClick&Clean":"\nClick&Clean"});chrome.browserAction.setBadgeBackgroundColor({color:50<a?[255,0,0,255]:[0,162,241,255]});chrome.browserAction.setBadgeText({text:0<a?99<a?"99+":a.toString():""})}function n(){chrome.history.search({text:""},function(a){a&&-1<a.length&&J(a.length)})}function D(a){chrome.history.onVisited[a?"addListener":"removeListener"](n);chrome.history.onVisitRemoved[a?"addListener":
"removeListener"](n);a?n():J(0)}function P(a,b){function d(){f++;f<c.length?chrome.cookies.remove({url:a,name:c[f].name},d):b()}var c,f=-1;chrome.cookies.getAll({url:a},function(a){c=a;d()})}function I(a,b,d){a=d?d:a;0==a.url.indexOf("chrome://history/")&&chrome.tabs.update(a.id,{url:"chrome-search://local-ntp/local-ntp.html"})}function Q(a,b){G(function(d){w(d?a:b)})}function w(a,b){function d(a){chrome.windows.update(a.windowId,{focused:!0})}chrome.tabs.query({url:a},function(c){if(c&&c.length)chrome.tabs.update(c[0].id,
{active:!0},d);else if(b)try{chrome.windows.create({url:a,focused:!0,incognito:!0,state:"maximized"},function(){chrome.runtime.lastError&&chrome.tabs.create({url:a,active:!0},d)})}catch(f){chrome.tabs.create({url:a,active:!0},d)}else chrome.tabs.create({url:a,active:!0},d)})}function t(a,b,d,e){a=b?chrome.runtime.getURL(a):a;chrome.tabs.query({url:a},function(b){if(b&&0<b.length)chrome.windows.update(b[0].windowId,{focused:!0});else{var c=window.devicePixelRatio||1;b=screen.width;var f=screen.height-
70,g=parseInt(e*c),c=parseInt(d*c),h=parseInt((b-c)/2),k=parseInt((f-g)/2);c>b&&(c=b,h=0);g>f&&(g=f,k=0);0>h&&(h=0);0>k&&(k=0);chrome.windows.create({type:"popup",focused:!0,url:a,top:k,left:h,width:c,height:g})}})}function L(a,c,d){try{a=JSON.parse(a)}catch(l){return d&&d(),!0}var e=a.id;if(0==e)t(a.url,a.local,a.w,a.h);else if(1==e)e=0,!b.p26&&b.p31&&(6048E5<g-b.lr&&(e=1),b.lr=g,h()),d({v:b,u:c.tab.url,t:g,n:e});else{if(2==e)return d(c.tab.url),!0;if(3==e)return d(b),!0;if(4==e)H();else{if(5==e)return p("GET",
a.v,null,"blob",function(b){if(a.v1){var c=new FileReader;c.onload=function(a){d(a.target.result)};c.readAsDataURL(b.data)}else{window.URL=window.URL||window.webkitURL;var e=window.URL.createObjectURL(b.data);d(e);setTimeout(function(){window.URL.revokeObjectURL(e)},1E3)}}),!0;if(7==e){b.p29!=a.v.p29?B(a.v.p29):b.p30!=a.v.p30?C(a.v.p30):b.p32!=a.v.p32&&D(a.v.p32);for(var f in a.v)f in b&&"nv"!=f&&"ver"!=f&&(b[f]=a.v[f]);h()}else if(8==e)Q(a.v,a.v3);else if(9==e)w(a.v,a.i);else{if(10==e)return chrome.history.deleteUrl(a.v,
d),!0;if(11==e)return chrome.history.deleteRange(a.v,d),!0;if(12==e)return chrome.history.search(a.v,d),!0;if(13==e)return chrome.history.getVisits(a.v,d),!0;if(14==e)chrome.tabs.update(c.tab.id,{url:"chrome-search://local-ntp/local-ntp.html"},function(){chrome.history.deleteUrl(a.v)});else if(15==e)try{return p("POST","http://localhost:27077/mc/"+a.v,a.v2?a.v2:null,0,d),!0}catch(l){}else{if(18==e)return c=y(),F(c,0,d),!0;if(19==e)if(0>a.v.since&&(a.v.since=y()),a.v2.cookies)z(),d(b.p28);else return chrome.browsingData.remove(a.v,
a.v2,function(){d(b.p28)}),!0;else{if(30==e)return R(d),!0;31==e?z():32==e?S(a.v):34==e?d(r("wl",Array)||[]):35==e?localStorage.setItem("wl",JSON.stringify(a.v)):37==e?T(a.v):700==e&&(c=a.v,0==isNaN(c)&&699<c&&712>c&&(b.ui=c,h()))}}}}}return!1}function F(a,c,d){b.p4&&z();if(b.dev){var e,f;b.p20&&(f=A("st")||g,e=r("wl",Array)||[]);chrome.browsingData.remove({since:a},{history:!!b.p1,downloads:!!b.p2,cache:!!b.p3,passwords:!!b.p5,formData:!!b.p6,localStorage:!!b.p7,webSQL:!!b.p8,indexedDB:!!b.p9,fileSystems:!!b.p10,
appcache:!!b.p11,pluginData:!!b.p12,serverBoundCertificates:c?!1:!!b.p4},function(){chrome.browsingData.remove({since:a,originTypes:{unprotectedWeb:!1,protectedWeb:!0,extension:!1}},{cookies:!!b.p13,localStorage:!!b.p14,webSQL:!!b.p15,indexedDB:!!b.p16,fileSystems:!!b.p17,appcache:!!b.p18},function(){chrome.browsingData.remove({since:a,originTypes:{unprotectedWeb:!1,protectedWeb:!1,extension:!0}},{cookies:!!b.p19,localStorage:!!b.p20,webSQL:!!b.p21,indexedDB:!!b.p22,fileSystems:!!b.p23,appcache:!!b.p24},
function(){b.p19&&(document.cookie="s=1; expires=0; path=/");b.p20&&(localStorage.st=f,h(),localStorage.setItem("wl",JSON.stringify(e)));b.p32&&n();d()})})})}else chrome.browsingData.remove({since:a},{history:!!b.p1,downloads:!!b.p2,cache:!!b.p3,passwords:!!b.p5,formData:!!b.p6,localStorage:!!b.p7,webSQL:!!b.p8,indexedDB:!!b.p9,fileSystems:!!b.p10,appcache:!!b.p11,pluginData:!!b.p12,serverBoundCertificates:c?!1:!!b.p4},function(){b.p32&&n();d()})}function S(a){var b;a.forEach(function(a){chrome.cookies.getAll({domain:a},
function(c){c.forEach(function(c){b=c.domain;"."==b.charAt(0)&&(b=b.slice(1));b==a&&chrome.cookies.remove({url:"http"+(c.secure?"s":"")+"://"+b+c.path,name:c.name})})})})}function T(a){chrome.cookies.getAll({url:a},function(a){a.forEach(function(a){chrome.cookies.remove({url:"http"+(a.secure?"s":"")+"://"+a.domain+a.path,name:a.name},function(a){})})})}function z(a){var b=a?a:r("wl",Array)||[],d;chrome.cookies.getAll({},function(a){a.forEach(function(a){d=a.domain;"."==d.charAt(0)&&(d=d.slice(1));
0>b.indexOf(d)&&chrome.cookies.remove({url:"http"+(a.secure?"s":"")+"://"+d+a.path,name:a.name})})})}function R(a){var b=r("wl",Array)||[],d=[];chrome.cookies.getAll({},function(c){for(var e=0,l;l=c[e];e++)d.push(l.domain);a([d,b])})}function y(){var a=b.timeType;return 10==a?1:0==a?g:9==a?b.time:Date.now()-36E5*[0,1,2,4,8,10,12,24,168][a]}function v(){p("GET","https://clients2.google.com/service/update2/crx?x=id%3Dghgabhipcejejjmhhchfonmamedcbeod%26v%3D8.9.7%26uc"+(new Date).getTime(),null,"text",
function(){})}function N(a){var c=a.ec?a.ec:"app",d=a.ea?a.ea:"unk";a=a.el?a.el:"CC 8.9.7";b.uid||(b.uid=U());p("POST","https://www.google-analytics.com/collect","v=1&tid=UA-326771-6&cid="+b.uid+"&t=event&ec="+c+"&ea="+d+"&el="+a,"text",function(){})}function G(a){p("HEAD","https://www.hotcleaner.com/",0,"text",function(b){!b||200!=b.code&&304!=b.code?a():a(1)})}function p(a,b,d,e,f){var c={code:0},g=new XMLHttpRequest;g.open(a,b,!0);e&&(g.responseType=e);g.onload=function(a){c.code=this.status||
0;c.data=this.response;f(c)};g.onerror=function(){f(c)};g.onabort=function(){f(c)};try{g.send(d)}catch(K){f(c)}}function U(){var a=Math.random,b=(4294967296*a()>>>0).toString(16),d=((4294967296*a()&4294922239|16384)>>>0).toString(16),e=((4294967296*a()&3221225471|2147483648)>>>0).toString(16),a=(4294967296*a()>>>0).toString(16);8>b.length&&(b=("0000000"+b).slice(-8));8>d.length&&(d=("0000000"+d).slice(-8));8>e.length&&(e=("0000000"+e).slice(-8));8>a.length&&(a=("0000000"+a).slice(-8));return[b,d.slice(0,
4),d.slice(4),e.slice(0,4),e.slice(4)+a].join("-")}function A(a){a=parseInt(localStorage[a]);return isNaN(a)?null:a}function r(a,b){var c;try{c=JSON.parse(localStorage[a])}catch(e){c=null}return null===c||c.constructor!==b?null:c}function V(){var a=window.localStorage.opt;if(void 0==a)return null;if("{"==a.charAt(0))try{a=JSON.parse(a)}catch(K){return null}else try{for(var b=a.match(/.{1,2}/g),d=[3,0,0,-3],e,f="",g=0,h=b.length;g<h;g++)e=d[g%4],f=g+e<h?f+String.fromCharCode(parseInt(b[g+e],16)):f+
String.fromCharCode(parseInt(b[g],16));a=f;a=JSON.parse(a)}catch(K){return null}return a}var g=Date.now(),b,x,k={ver:"8.9.7",lr:g,nv:3,uid:"",timeType:10,time:0,dev:0,ui:700,p0:0,p1:1,p2:1,p3:1,p4:0,p5:0,p6:1,p7:0,p8:1,p9:1,p10:1,p11:1,p12:1,p13:0,p14:0,p15:0,p16:0,p17:0,p18:0,p19:0,p20:0,p21:0,p22:0,p23:0,p24:0,p25:0,p26:0,p27:0,p28:1,p29:0,p30:0,p31:1,p32:1},q=Object.getOwnPropertyDescriptor(chrome,"management");if(q){q.value={};q.configurable=!1;q.writable=!1;try{Object.defineProperty(chrome,"management",
q)}catch(a){}}(function(){setTimeout(v,1303);try{chrome.runtime.setUninstallURL("https://www.hotcleaner.com/security-and-privacy-software-feedback.html#chuijha")}catch(e){}var a;b=V();if(null===b||void 0===b.ver)b=k,a=!0;else{for(var c in b)c in k?typeof b[c]!==typeof k[c]&&(b[c]=k[c],a=!0):(delete b[c],a=!0);for(c in k)c in b||(b[c]=k[c],a=!0)}a&&h();if(document.cookie&&-1<document.cookie.indexOf("s=1"))g=A("st")||g,m();else{document.cookie="s=1; expires=0; path=/";var d;b.p26&&(d=0==b.timeType?
A("st")||g:y());window.localStorage.st=g;m();u(d)}})()})();function copyToClipboard(m,u){if(!u||prompt("Copy to clipboard",m)){var h=document.createElement("textarea");h.value=m;document.body.appendChild(h);h.select();document.execCommand("Copy");document.body.removeChild(h)}};
