// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
(function(){function B(){function l(){var b=this.id;m!=b&&(m&&(v(m).className="nav"),m=b,this.className="nav act",g(b))}function g(b){var a,C=v("box");if("menu0"==b)a=[3,"red","close.png",0,7,0,"options1.png",18,3,"magenta","clear.png",1,7,0,"options1.png",18,7,0,"tabs1.png",2,3,"violet","cache.png",3,7,0,"trash1.png",4,3,"violet","history.png",5,7,0,"trash1.png",6,0,"blue",t?"quickscan.png":"extensions.png",t?8:7,3,"violet","downloads.png",9,7,0,"trash1.png",10,0,"choko","cookie.png",15,7,0,"trash1.png",
16,0,"seawave",t?"cleanup.png":"memory.png",t?12:13,3,"violet","security.png",14,0,"carbon","incognito.png",11,0,"teal","report.png",17,0,"magenta","options.png",18,7,0,"themes.png",19,0,"green","updates.png",20,2,["yellow","bluefb","redgp","bluetw","redyt"],["rate32.png","facebook32.png","gplus32.png","twitter32.png","youtube32.png"],21];else if("menu1"==b)a=[3,"seawave","plugins.png",0,3,"green","extensions.png",1,3,"orange","experiments.png",2,3,"magenta","internals.png",3,0,"violet","dns.png",
4,3,"violet","history.png",5,0,"violet","cache.png",6,0,"red","key.png",7,3,"blue","version.png",8,7,0,"arrow1.png",9,0,"red","conflicts.png",10,0,"teal","policies.png",11,0,"blue","releases.png",12,7,0,"calendar1.png",13,0,"blue","credits.png",14,0,"teal","bug.png",15];else if("menu2"==b)a=[3,"green","winsec.png",0,3,"blue","info.png",1,3,"red","uninstall.png",2,3,"violet","defragmenter.png",3,3,"magenta","sound.png",4,3,"marine","network.png",5,7,0,"connect.png",6,7,0,"wireless.png",7,3,"teal",
"devices.png",8,3,"violet","display.png",9,3,"blue","services.png",10,3,"seawave","directx.png",11];else if("menu3"==b){d(c.runtime.getURL("lnAa.html"),0);window.close();return}var F=0;b=c.i18n.getMessage(b).split(";");for(var h=document.createDocumentFragment(),f,q,r,k,e,g,l,m,p,n,u=0;u<a.length;u+=4)l=u/4,r=a[u],g=a[u+1],m=a[u+2],2==r?(k=new Uint8Array(1),crypto.getRandomValues(k),k=k[0]%g.length,l="i"+(l+k),g=g[k],m="i/menu/"+m[k],n=b[a[u+3]+k]):(l="i"+l,m="i/menu/"+m,n=b[a[u+3]]),7>r?
(p=0,f=document.createElement("div"),q=document.createElement("div"),e=document.createElement("div"),k=new Image,g="btn "+g,2<r?(g+=" wide",f.className="btnBoxWide"):f.className="btnBox",q.id=l,q.className=g,k.className="icn",e.className="txt0",k.dataset.url=k.src=m,e.textContent=n,q.appendChild(k),q.appendChild(e),f.appendChild(q),h.appendChild(f)):(r=document.createElement("div"),f=document.createElement("div"),k=new Image,k.src=m,r.id=l,r.className="adt a"+p,k.className="icnm",f.className="txt1",
f.textContent=n,r.appendChild(k),q.insertBefore(r,e),q.insertBefore(f,e),p++),F++;C.innerHTML="";C.appendChild(h);C.style.display=""}function p(b){b=b.target.id?b.target:b.target.parentElement;var a;"menu0"==m?(a=parseInt(b.id.slice(1)),0==a?c.runtime.sendMessage(JSON.stringify({id:4})):1==a?(c.runtime.sendMessage(JSON.stringify({id:0,local:1,url:"uMHZ.html",w:770,h:500})),window.close()):2==a?x(b):3==a?(c.runtime.sendMessage(JSON.stringify({id:0,local:1,url:"uMHZ.html",w:770,
h:500})),window.close()):4==a?D(0,0,0):5==a?t?y("https://www.hotcleaner.com/cache-viewer.html",c.runtime.getURL("OSfL.html")):d(e+"cache/"):6==a?x(b,"cache"):7==a?y("https://www.hotcleaner.com/clear-browsing-history.html",c.runtime.getURL("bNgD.html")):8==a?x(b,"history"):9==a?z("https://www.hotcleaner.com/clickclean-scan-for-malware.html",e+"extensions/",1):10==a?d(e+"downloads/"):11==a?x(b,"downloads"):12==a?y("https://www.hotcleaner.com/cookie-wiper.html",c.runtime.getURL("kBT.html")):
13==a?x(b,"cookies"):14==a?t?w(115):d(e+"system/"):15==a?z("https://www.hotcleaner.com/clickclean-app.html#chvijha","https://myaccount.google.com/intro/privacycheckup/1",1):16==a?c.windows.create({url:void 0,incognito:!0,focused:!0,top:-3,left:-8,width:screen.availWidth+16,height:screen.availHeight+6}):17==a?z("https://www.hotcleaner.com/security-and-privacy-software-feedback.html#chvijha","https://plus.google.com/101494399825495328979",1):18==a?(c.runtime.sendMessage(JSON.stringify({id:0,local:1,
url:"uMHZ.html",w:770,h:500})),window.close()):19==a?d("https://www.hotcleaner.com/clickclean-appearance.html",0):20==a?z("https://www.hotcleaner.com/clickclean_chrome_update_checker.html#chvijha","https://chrome.google.com/webstore/detail/clickclean/ghgabhipcejejjmhhchfonmamedcbeod/reviews",1):21==a?d("https://chrome.google.com/webstore/detail/clickclean/ghgabhipcejejjmhhchfonmamedcbeod/reviews"):22==a?d("https://www.facebook.com/clickclean",0):23==a?d("https://plus.google.com/101494399825495328979/posts",
0):24==a?d("https://twitter.com/intent/user?screen_name=clickclean",0):25==a&&d("https://youtube.com/subscription_center?add_user=YTMoo",0)):"menu1"==m?(a=parseInt(b.id.slice(1)),0==a?d(e+"plugins/"):1==a?d(e+"extensions/"):2==a?d(e+"flags/"):3==a?d(e+"net-internals/"):4==a?d(e+"dns/"):5==a?y("https://www.hotcleaner.com/clear-browsing-history.html",c.runtime.getURL("bNgD.html")):6==a?t?y("https://www.hotcleaner.com/cache-viewer.html",c.runtime.getURL("OSfL.html")):d(e+"cache/"):
7==a?c.windows.create({url:"y.html",type:"popup",focused:!0,width:350,height:216}):8==a?d("o"==e.charAt(0)?e+"about/":e+"version/"):9==a?d("https://chrome.googleblog.com/"):10==a?d(e+(t?"conflicts/":"crashes/")):11==a?d(e+"policy/"):12==a?d("https://googlechromereleases.blogspot.com/"):13==a?d("https://www.chromium.org/developers/calendar"):14==a?d("o"==e.charAt(0)?e+"about/credits/":e+"credits/"):15==a&&d("https://code.google.com/p/chromium/issues/list")):"menu2"==m&&(a=parseInt(b.id.slice(1))+
100,w(a))}function w(b){c.runtime.sendMessage(JSON.stringify({id:15,v:"00"+b.toString(16)}),function(){})}function D(b,a,e){c.tabs.query(a?{active:!0}:{},function(d){d.forEach(function(h,f){a?c.tabs.reload(h.id):f?c.tabs.remove(h.id):c.tabs.update(h.id,{url:b?"about:blank":"chrome-search://local-ntp/local-ntp.html"});e&&f==d.length-1&&setTimeout(e,500)})})}function x(b,a,e){function d(){h.p28&&window.Audio&&(new Audio("i/erased.ogg")).play();setTimeout(function(){f.src="i/menu/done.png";setTimeout(function(){f.src=
f.dataset.url;e&&c.tabs.query({},function(a){a.forEach(function(a,b){c.tabs.remove(a.id)})})},900);E=!1},300)}if(!E){E=!0;var h,f=a?b.previousElementSibling:b.firstElementChild;f.src="i/menu/wipe.gif";c.runtime.sendMessage(JSON.stringify({id:3}),function(b){h=b;a?(b={id:19,v:{since:-1},v2:{}},b.v2[a]=!0,c.runtime.sendMessage(JSON.stringify(b),d)):h.p0||e?D(e,0,function(){c.runtime.sendMessage(JSON.stringify({id:18}),d)}):c.runtime.sendMessage(JSON.stringify({id:18}),function(){h.p25?D(0,1,d):d()})})}}
function y(b,a){c.runtime.sendMessage(JSON.stringify({id:8,v:b,v3:a}))}function d(b,a){c.runtime.sendMessage(JSON.stringify({id:9,v:b,i:a?1:0}))}function z(b,a,d){B(function(e){c.runtime.sendMessage(JSON.stringify({id:9,v:e?b:a,i:d?1:0}))})}function B(b){G("HEAD","https://www.hotcleaner.com/",0,"text",function(a){!a||200!=a.code&&304!=a.code?b():b(1)})}function G(b,a,d,e,c){var f={code:0},g=new XMLHttpRequest;g.open(b,a,!0);e&&(g.responseType=e);g.onload=function(a){f.code=this.status||0;f.data=this.response;
c(f)};g.onerror=function(){c(f)};g.onabort=function(){c(f)};try{g.send(d)}catch(r){c(f)}}function H(b,a){var c=document.createElement("link");c.rel="stylesheet";c.type="text/css";c.href=a;b.appendChild(c)}function v(b){return A.querySelector("#"+b)}var n,t,E=!1,e=/Comodo/.test(navigator.appVersion)?"dragon://":/OPR/.test(navigator.appVersion)?"opera://":"chrome://",m="menu0";c.runtime.sendMessage(JSON.stringify({id:3}),function(b){function a(a){var b=document.createElement("div");b.className=0==a?
"nav act":"nav";b.id="menu"+a;b.textContent=e[a];b.addEventListener("click",l,!1);return b}n=b;H(A,"css/BxZD.css");var e=c.i18n.getMessage("menu").split(";");b=document.createDocumentFragment();var d=document.createElement("div"),h=document.createElement("div");d.id="menu";h.id="box";701==n.ui?h.style.setProperty("filter","sepia(.5)"):702==n.ui?h.style.setProperty("filter","grayscale(1) brightness(1.17)"):703==n.ui?h.style.setProperty("filter","invert(1) sepia(1) saturate(0) brightness(1.7) contrast(.8)"):
704==n.ui?h.style.setProperty("filter","invert(.9) sepia(1) brightness(.85) hue-rotate(20deg)"):705==n.ui?h.style.setProperty("filter","invert(.9) sepia(1) brightness(0.95) hue-rotate(155deg)"):706==n.ui&&h.style.setProperty("filter","invert(.87) sepia(1) brightness(0.95) hue-rotate(0deg)");b.appendChild(d);b.appendChild(h);for(var f=0,q=e.length;f<q;f++)2!=f&&d.appendChild(a(f));A.appendChild(b);g(m);h.addEventListener("click",p,!1);/Win/.test(navigator.platform)&&c.runtime.sendMessage(JSON.stringify({id:15,
v:"000E"}),function(b){b&&b.data&&(t=b.data,d.insertBefore(a(2),v("menu3")),setTimeout(function(){v("i9").firstElementChild.src="i/menu/quickscan.png";v("i14").firstElementChild.src="i/menu/cleanup.png";var a=c.i18n.getMessage("menu0").split(";");v("i9").firstElementChild.nextElementSibling.textContent=a[8];v("i14").firstElementChild.nextElementSibling.textContent=a[12]},1))})})}var w,A,c={};if("chrome"in window){var p,l;for(l in chrome)if("object"==typeof chrome[l]&&(p=Object.getOwnPropertyDescriptor(chrome,
l))){c[l]=p.value;p.value={};p.configurable=!1;p.writable=!1;try{Object.defineProperty(chrome,l,p)}catch(I){c[l]=chrome[l]}}}"attachShadow"in Element.prototype&&(w=Element.prototype.attachShadow,Element.prototype.attachShadow=void 0);window.addEventListener("DOMContentLoaded",function(){var c=document.body,g;if(g=w){b:{if(navigator.appVersion&&(g=navigator.appVersion.indexOf("Chrome/"),-1<g)){g=parseInt(navigator.appVersion.slice(g+7));break b}g=0}g=53<g}A=g?w.call(c,{mode:"closed"}):c;B()},!1)})();
