// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
(function(){function P(a){Q(a.u);f=a.v;A=a.t;y();var b,c,d;document.title=chrome.i18n.getMessage("m2");R();b=chrome.i18n.getMessage("cleaner2").split(";");d=document.getElementsByClassName("section");for(var e=0;3>e;e++)d[e].childNodes[0].textContent=b[e];d=document.getElementsByClassName("subtitle");for(e=0;3>e;e++)d[e].textContent=b[e+3];d=g("timeType");b=chrome.i18n.getMessage("cleaner3").split(";");g("timeLabel").textContent=b[0];for(e=1;12>e;e++)c=document.createElement("option"),c.textContent=
b[e],d.appendChild(c);d.selectedIndex=f.timeType;d.addEventListener("change",B,!1);H();b=chrome.i18n.getMessage("cleaner4").split(";");c=chrome.i18n.getMessage("cleaner5").split(";");for(e=0;33>e;e++){d=g("p"+e);f[d.id]&&d.setAttribute("on",!0);d.addEventListener("click",S,!1);d=d.nextElementSibling;"more"==d.className&&(d.title=c[0],d.addEventListener("click",T,!1),d=d.nextElementSibling);if("run"==d.className||"del"==d.className)d.title=0==e?c[1]:25==e?c[2]:26==e?c[3]:27==e?c[4]:28==e?c[5]:b[e],
d.addEventListener("click",U,!1),d=d.nextElementSibling;d.textContent=d.title=b[e]}document.body.addEventListener("mousedown",function(a){"select"!=a.target.localName&&"input"!=a.target.localName&&"p"!=a.target.localName&&a.preventDefault()},!1);b=document.getElementsByTagName("label");e=0;for(d=b.length;e<d;e++)b[e].addEventListener("mouseup",function(a){this.control&&setTimeout(function(){a.target.control.blur()},100)},!1);V();n(document.body,"dbk");d=g("timeType");9==f.timeType?n(d,"w32"):n(d,
"w255");a.n&&h("m3",function(){u("https://www.hotcleaner.com/clear-browsing-history.html",chrome.runtime.getURL("bNgD.html"))},0,0,"b2",0,"shade-bg-white");W()}function w(){chrome.runtime.sendMessage(JSON.stringify({id:7,v:f}))}function V(){chrome.tabs.getCurrent(function(a){var b=chrome.runtime.getURL("uMHZ.html");chrome.tabs.query({url:b},function(b){for(var c=0,e=b.length;c<e;c++)b[c].id!=a.id&&chrome.tabs.remove(b[c].id);chrome.windows.getCurrent({},function(b){var c=window.devicePixelRatio||
1,d=screen.width,e=screen.height-70,f=parseInt(500*c),c=parseInt(770*c),g=parseInt((d-c)/2),k=parseInt((e-f)/2);c>d&&(c=d,g=0,document.body.style.zoom=window.innerWidth/850);f>e&&(f=e,k=0);0>g&&(g=0);0>k&&(k=0);"normal"==b.type?chrome.windows.create({type:"popup",focused:!0,tabId:a.id,top:k,left:g,width:c,height:f}):chrome.windows.update(b.id,{state:"normal",width:c,height:f})})})})}function W(){/Win/.test(navigator.platform)?chrome.runtime.sendMessage(JSON.stringify({id:15,v:"000E"}),function(a){C=
a?1:2}):C=3}function U(a){a=this.parentElement.firstElementChild.id;"p5"!=a||f[a]?"p20"!=a||f[a]?D(a):h("m20b",D,p,a):h("m5b",D,p,a)}function D(a){function b(){d.className="ghk";r(!1,!1);I();(28==a||f.p28)&&J();m(0==a||25==a||28==a?"m8":"m7",500);setTimeout(function(){d.className="chk"},500)}m();r(!0,!0);var c=K(),d=g(a);a=a.slice(1);27==a&&L();d.className="wipe";28==a?b():M(a,c,b)}function X(){function a(a){for(var b,c=0,d=l.length;c<d;c++)b=g("p"+l[c]),b.hasAttribute("on")&&(b.className=a)}function b(){f.p28&&
J();m("m7",1E3);I();setTimeout(function(){a("chk");r(!1,0);f.p27&&L()},1E3)}function c(){setTimeout(function(){g("p"+l[k]).className="ghk";d()},10)}function d(){k++;if(k<l.length){var a=l[k];f["p"+a]?M(a,e,c):d()}else b()}r(!0,!0);m();var e=K(),k=-1,l;l=f.dev?[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]:[0,1,2,3,4,5,6,7,8,9,10,11,12,25];a("wipe");d()}function M(a,b,c){var d=chrome.browsingData,e={since:b};if(13>a)0==a?N(0,c):1==a?d.removeHistory(e,c):2==a?d.removeDownloads(e,
function(){d.removeDownloads(e,c)}):3==a?d.removeCache(e,c):4==a?d.remove(e,{serverBoundCertificates:!0},function(){chrome.runtime.sendMessage(JSON.stringify({id:31}));c()}):5==a?d.removePasswords(e,c):6==a?d.removeFormData(e,c):7==a?d.removeLocalStorage(e,c):8==a?d.removeWebSQL(e,c):9==a?d.removeIndexedDB(e,c):10==a?d.removeFileSystems(e,c):11==a?d.removeAppcache(e,c):12==a&&d.removePluginData(e,c);else if(19>a)e.originTypes={unprotectedWeb:!1,protectedWeb:!0,extension:!1},13==a?d.removeCookies(e,
c):14==a?d.removeLocalStorage(e,c):15==a?d.removeWebSQL(e,c):16==a?d.removeIndexedDB(e,c):17==a?d.removeFileSystems(e,c):18==a&&d.removeAppcache(e,c);else if(25>a)if(e.originTypes={unprotectedWeb:!1,protectedWeb:!1,extension:!0},19==a)d.removeCookies(e,function(){document.cookie="s=1; expires=0; path=/";c()});else if(20==a){var g=Y("wl",Array)||[];d.removeLocalStorage(e,function(){localStorage.st=A;localStorage.setItem("opt",JSON.stringify(f));localStorage.setItem("wl",JSON.stringify(g));c()})}else 21==
a?d.removeWebSQL(e,c):22==a?d.removeIndexedDB(e,c):23==a?d.removeFileSystems(e,c):24==a&&d.removeAppcache(e,c);else 25==a?N(1,c):c()}function N(a,b){chrome.tabs.getCurrent(function(c){chrome.tabs.query(a?{active:!0}:{},function(d){var e=0;d.forEach(function(b,d){c.id==b.id?0==d&&e++:a?chrome.tabs.reload(b.id):d>e?chrome.tabs.remove(b.id):chrome.tabs.update(b.id,{url:"chrome-search://local-ntp/local-ntp.html"})});b&&setTimeout(b,500)})})}function L(){chrome.tabs.getCurrent(function(a){chrome.tabs.remove(a.id)})}
function I(){chrome.history.search({text:""},function(a){a&&-1<a.length&&(a=a.length,chrome.browserAction.setTitle({title:0<a?"Visited Pages: "+a+"\nClick&Clean":"\nClick&Clean"}),chrome.browserAction.setBadgeBackgroundColor({color:50<a?[255,0,0,255]:[0,162,241,255]}),chrome.browserAction.setBadgeText({text:0<a?99<a?"99+":a.toString():""}))})}function T(a){a=parseInt(this.previousElementSibling.id.slice(1));var b=[7,8,9,10,13,14,15,16,17,19,20,21,22,23],c=/Comodo/.test(navigator.appVersion)?"dragon://":
/OPR/.test(navigator.appVersion)?"opera://":"chrome://";if(1==a)u("https://www.hotcleaner.com/clear-browsing-history.html",chrome.runtime.getURL("bNgD.html"));else{if(2==a)c+="downloads/";else if(3==a){if(1==C){u("https://www.hotcleaner.com/cache-viewer.html",chrome.runtime.getURL("OSfL.html"));return}c+="view-http-cache"}else{if(4==a){u("https://www.hotcleaner.com/cookie-wiper.html",chrome.runtime.getURL("kBT.html"));return}-1<b.indexOf(a)?c+="settings/cookies":5==
a?c+="settings/passwords":6==a?c+="settings/autofill":11==a||18==a||24==a?c+="appcache-internals":12==a?c+="plugins":26==a&&(c+="version")}chrome.runtime.sendMessage(JSON.stringify({id:9,v:c}))}}function Z(a){f.time=a;w()}function B(){var a=g("timeType"),b=a.selectedIndex;f.timeType=b;9==b?t(a,"w255","w32"):t(a,"w32","w255");H();w()}function H(){var a=g("time");9==f.timeType?(a.firstElementChild.hasAttribute("data-time")||calInit(a.firstElementChild,f.time,1,Z),t(a,"nvw","dbk")):(t(a,"dbk","nvw"),
(a=g("cal"))&&t(a,"dbk","nvw"))}function K(){var a=f.timeType;return 10==a?1:0==a?A:9==a?f.time:Date.now()-36E5*[0,1,2,4,8,10,12,24,168][a]}function S(a){a=this.id;"p5"!=a||f[a]?"p20"!=a||f[a]?E(a):h("m20a",E,p,a):h("m5a",E,p,a)}function E(a){var b=g(a);b.hasAttribute("on")?(b.removeAttribute("on"),f[a]=0):(b.setAttribute("on",!0),f[a]=1);w()}function r(a,b,c){var d=g("shade"),e=g("clr");e.disabled=g("reset0").disabled=g("reset1").disabled=g("reset2").disabled=g("dev").disabled=a;c?n(d,c):(z(d,"shade-bg-default"),
z(d,"shade-bg-white"));d.style.height=a?g("tab").scrollHeight+"px":"";b?e.setAttribute("on",!0):e.removeAttribute("on")}function m(a,b){var c=g("msg");a?(c.textContent=chrome.i18n.getMessage(a)+"!",n(c,"top48"),c.t&&(clearTimeout(c.t),c.t=null),c.t=setTimeout(m,b)):z(c,"top48")}function h(a,b,c,d,e,f,l){function k(){q();b(d)}function m(){q();c(d)}function q(){t(n,"dbk","nvw");b&&p.removeEventListener("click",k,!1);c&&h.removeEventListener("click",m,!1);r(!1)}r(!0,!1,l?l:"shade-bg-default");var n=
g("alert");l=n.firstElementChild.nextElementSibling;var h=l.nextElementSibling.firstElementChild,p=h.nextElementSibling;l.textContent=chrome.i18n.getMessage(a);p.textContent=chrome.i18n.getMessage(e?e:"b0");h.textContent=chrome.i18n.getMessage(f?f:"b1");c?t(h,"nvw","ibk"):t(h,"ibk","nvw");t(n,"nvw","dbk");c&&(h.addEventListener("click",m,!1),h.focus());b&&(p.addEventListener("click",k,!1),p.focus())}function q(a){var b=this.id,c="about:blank";"support"==b||"help"==b||"logo"==b||"fox"==b?aa(function(a){a?
("support"==b?c="https://www.hotcleaner.com/security-and-privacy-software-feedback.html#chvijha":"fox"==b?c="https://www.hotcleaner.com/clickclean_firefox.html":"help"==b?c="https://www.hotcleaner.com/clickclean-quick-start-guide.html":"logo"==b&&(c="https://www.hotcleaner.com/"),F(c,!0)):("support"==b?c="https://www.facebook.com/clickclean":"fox"==b?c="https://addons.mozilla.org/en-us/firefox/addon/clickclean/":"help"==b?c="https://www.facebook.com/clickclean":"ssl"==b?c="https://support.google.com/websearch/answer/173733":
"logo"==b&&(c="https://chrome.google.com/webstore/detail/ghgabhipcejejjmhhchfonmamedcbeod"),F(c,!1))}):("ctrb"==b?c=chrome.runtime.getURL("lnAa.html"):"ghsty"==b?c="https://history.google.com/history/settings?st=tr":"appearance"==b?c="https://www.hotcleaner.com/clickclean-appearance.html":"sync"==b&&(c="https://www.google.com/settings/chrome/sync"),F(c,!1))}function R(){function a(a,b,c,f,h){a=g(a);b&&("web"==a.className?a.firstElementChild.textContent=b:a.textContent=b);c&&(a.title=c);-1<
h&&(a.sid=h,n(a,"share"+h));f&&a.addEventListener("click",f,!1)}var b=chrome.i18n.getMessage("cleaner1").split(";");chrome.i18n.getMessage("share").split(";");var c=new Uint8Array(1);crypto.getRandomValues(c);c=c[0]%7;a("logo","v"+f.ver,0,q);a("fox","Get for Firefox!",0,q);a("ctrb",b[0],b[2],q);a("clr",b[3],0,X);a("hsty",b[4],b[5],function(){u("https://www.hotcleaner.com/clear-browsing-history.html",chrome.runtime.getURL("bNgD.html"))});a("support",b[6],0,q);a("help",b[7],0,q);a("reset0",
b[8],b[13],G);a("reset1",b[9],b[13],G);a("reset2",b[10],b[13],G);a("dev",b[11],b[12],function(){f.dev?(f.dev=0,w(),y()):h("m4",function(){f.dev=1;w();y()},p)});a("export",b[14],0,ba);a("import",b[15],0,ca);a("ghsty",b[16],b[16],q);a("sync",b[17],b[17],q);a("appearance",b[18],b[18],q)}function y(){for(var a=g("dev"),b=document.getElementsByClassName("dev"),c=f.dev?"nvw":"dbk",d=f.dev?"dbk":"nvw",e=0;e<b.length;++e)t(b[e],c,d);f.dev?a.setAttribute("on",!0):a.removeAttribute("on")}function G(a){a=parseInt(this.id.slice(5));
2!=a||f.p5?O(a):h("m5a",function(){O(2)},p)}function O(a){var b;0==a?b=[10,0,1,1,1,0,0,0,0,0,0,0,0,0,0]:1==a?b=[10,0,1,1,1,0,0,1,0,1,1,1,1,1,1]:2==a&&(b=[10,0,1,1,1,1,1,1,1,1,1,1,1,1,1]);f.timeType=b[0];f.time=b[1];f.p1=b[2];f.p2=b[3];f.p3=b[4];f.p4=b[5];f.p5=b[6];f.p6=b[7];f.p7=b[8];f.p8=b[9];f.p9=b[10];f.p10=b[11];f.p11=b[12];f.p12=b[13];g("timeType").selectedIndex=f.timeType;B();for(b=0;14>b;b++)a=g("p"+b),f[a.id]?a.setAttribute("on",!0):a.removeAttribute("on");f.p31=1;f.p32=1;g("p31").setAttribute("on",
!0);g("p32").setAttribute("on",!0)}function J(a){window.Audio&&(new Audio("i/erased.ogg")).play();a&&setTimeout(a,400)}function Q(a){for(var b=[chrome.runtime.getURL(""),"https://www.hotcleaner.com/","http://www.hotcleaner.com/"],c=0,d=b.length;c<d;c++)if(0==a.indexOf(b[c]))return;document.location.href="about:blank"}function u(a,b){r(1,0);m("m8",1500);chrome.runtime.sendMessage(JSON.stringify({id:8,v:a,v3:b}));r(0,0)}function F(a,b){chrome.runtime.sendMessage(JSON.stringify({id:9,v:a,i:b?1:0}))}
function ba(){chrome.runtime.sendMessage(JSON.stringify({id:34}),function(a){var b;a=JSON.stringify({opt:f,wl:a});Blob?b=new Blob([a],{type:"application/json;charset=UTF-8"}):BlobBuilder&&(b=new BlobBuilder,b.append(a),b=b.getBlob("application/json;charset=UTF-8"));da(b,"ClickClean-v"+f.ver+"-Options.json")})}function ca(){ea(1E5,function(a){try{a=JSON.parse(a)}catch(k){m("m12",1E3);return}var b=a.opt,c=f.ver,d=f.nv;a.wl&&chrome.runtime.sendMessage(JSON.stringify({id:35,v:a.wl}));for(var e in b)void 0!=
f[e]&&(f[e]=b[e]);f.ver=c;f.nv=d;g("timeType").selectedIndex=f.timeType;B();for(a=0;33>a;a++)el=g("p"+a),f[el.id]?el.setAttribute("on",!0):el.removeAttribute("on");y();m("m8",1E3)})}function ea(a,b){var c=g("openAs");c&&document.body.removeChild(c);c=document.createElement("input");c.id="openAs";c.className="nvw";c.type="file";document.body.appendChild(c);c.addEventListener("change",function(c){if((c=c.target.files)&&1==c.length&&c[0].size<a){var d=new FileReader;d.onload=function(a){b(a.target.result)};
d.readAsText(c[0])}else m("m12",1E3)},!1);c.click()}function da(a,b){r(1,0);var c=document.createElement("a"),d=window.URL||window.webkitURL;c.href=d.createObjectURL(a);c.setAttribute("download",b);c.click();setTimeout(function(){d.revokeObjectURL(c.href);r(0,0)},2E3)}function aa(a){var b=new Image;b.onload=function(){a(1)};b.onerror=function(){a()};b.onabort=function(){a()};b.src="https://www.hotcleaner.com/img/1.gif?t="+(new Date).getTime()}function Y(a,b){try{v=JSON.parse(localStorage[a])}catch(c){v=
null}return null===v||v.constructor!==b?null:v}function n(a,b){if(a){var c=a.className.split(" ");0>c.indexOf(b)&&(c.push(b),a.className=c.join(" "))}}function z(a,b){if(a){for(var c=a.className.split(" "),d=[],e=0,f=c.length;e<f;e++)c[e]!=b&&d.push(c[e]);a.className=d.join(" ")}}function t(a,b,c){a&&(z(a,b),n(a,c))}function g(a){return document.getElementById(a)}function p(){}var C,f,A;if("chrome"in window){var x=Object.getOwnPropertyDescriptor(chrome,"management");if(x){x.value={};x.configurable=
!1;x.writable=!1;try{Object.defineProperty(chrome,"management",x)}catch(a){}}}window.addEventListener("DOMContentLoaded",function(){chrome.runtime.sendMessage(JSON.stringify({id:1}),P)},!1)})();
