// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
(function(){function C(a){a:{for(var b=[chrome.runtime.getURL(""),"https://www.hotcleaner.com/","http://www.hotcleaner.com/","https://hotcleaner.com/","http://hotcleaner.com/"],c=0,d=b.length;c<d;c++)if(0==a.indexOf(b[c]))break a;document.location.href="about:blank"}a=chrome.i18n.getMessage("cookies").split(";");b=document.body.innerHTML;for(c=0;d=a[c];c++)b=b.replace(new RegExp("t"+(10+c),"gm"),d);document.body.innerHTML=b;h("sel0").addEventListener("click",w,!1);h("sel1").addEventListener("click",
w,!1);h("ref").addEventListener("click",x,!1);h("del0").addEventListener("click",D,!1);h("toc0").addEventListener("click",E,!1);h("toc1").addEventListener("click",F,!1);x();a=h("services");for(var b=[{n:"Google | G+, GMail, YouTube, ...",d0:"accounts.google.com",d1:"google.com",i:1},{n:"Facebook",d0:"facebook.com",i:2},{n:"Twitter",d0:"twitter.com",i:3},{n:"Yahoo",d0:"yahoo.com",i:4},{n:"Microsoft | SkyDrive, Live Mail, ...",d0:"login.live.com",d1:"live.com",i:5}],f=document.createDocumentFragment(),
e=0,g;g=b[e];e++)c=document.createElement("button"),c.className="btn float-left",c.title=g.n,c.setAttribute("data-d0",g.d0),g.d1&&c.setAttribute("data-d1",g.d1),d=new Image,d.className="mt3",d.src="i/fav/"+g.i+".png",c.appendChild(d),c.addEventListener("click",G,!1),f.appendChild(c);a.appendChild(f)}function x(){m(1);h("list0").innerHTML=h("list1").innerHTML="";chrome.runtime.sendMessage(JSON.stringify({id:30}),function(a){var b=a[0];a=a[1];var c=[],d,f,e=0,g=0,n=0;if(0<b.length){for(var l=0,k;k=
b[l];l++)"."==k.charAt(0)&&(b[l]=k.slice(1));b.sort(function(a,b){return a<b?-1:1});d=a.indexOf(b[0]);for(l=0;k=b[l];l++)f!=k&&(0<e&&(0>d?(c.push(e),g+=e):(a[d+1]=e,n+=e),e=0),d=a.indexOf(k),0>d&&c.push(k)),e++,f=k;0<e&&(0>d?(c.push(e),g+=e):(a[d+1]=e,n+=e))}y(0,c,1,1);y(1,a,0,0);h("cnt0").textContent=" ("+g+")";h("cnt1").textContent=" ("+n+")";m(0)})}function w(a){a=v(this,"on");for(var b=this.parentElement.nextElementSibling.children,c=0,d;d=b[c];c++)q(d.firstElementChild,"on",a),q(d,"on",a)}function H(a){var b=
this.parentNode.getAttribute("data-domain");chrome.runtime.sendMessage(JSON.stringify({id:9,v:"https://"+b+"/"}));a.stopPropagation()}function I(a){a.stopPropagation();a=this.parentNode;var b=a.parentNode.getAttribute("data-id"),c=a.getAttribute("data-domain"),d=parseInt(a.getAttribute("data-count"));chrome.runtime.sendMessage(JSON.stringify({id:32,v:[c]}));a.parentElement.removeChild(a);r(b,-d);1==b&&t()}function D(a){m(1);var b=this.parentElement.nextElementSibling;a=b.querySelectorAll(".item[on]");
if(0<a.length){for(var c=[],b=b.getAttribute("data-id"),d,f=0,e=0,g;g=a[e];e++)d=g.getAttribute("data-domain"),c.push(d),f+=parseInt(g.getAttribute("data-count")),g.parentElement.removeChild(g);chrome.runtime.sendMessage(JSON.stringify({id:32,v:c}));r(b,-f)}m(0)}function E(){m(1);z(1,0);t()}function F(a){m(1);z(0,1);t()}function t(){for(var a=[],b=h("list1").children,c=0,d;d=b[c];c++)a.push(d.getAttribute("data-domain"),0);chrome.runtime.sendMessage(JSON.stringify({id:35,v:a}));m(0)}function z(a,
b){var c=h("list"+a).querySelectorAll(".item[on]");if(0<c.length){for(var d=[],f=0,e;e=c[f];f++)d.push(e.parentNode.removeChild(e));A(a,b,d)}}function r(a,b){var c=h("cnt"+a),d=parseInt(c.textContent.slice(2));c.textContent=" ("+(d+b)+")"}function v(a,b){var c=a.hasAttribute(b);c?a.removeAttribute(b):a.setAttribute(b,!0);return!c}function q(a,b,c){c?a.setAttribute(b,!0):a.removeAttribute(b)}function J(a){var b=this.hasAttribute("on");if(a.shiftKey){if(0>u&&(u=this.parentNode.firstElementChild),a=
!b,b=u,this&&b){var c=this;c.getAttribute("data-domain")>b.getAttribute("data-domain")&&(c=b,b=this);for(;c&&c.getAttribute("data-domain")<=b.getAttribute("data-domain");)q(c,"on",a),q(c.firstElementChild,"on",a),c=c.nextElementSibling}}else v(this.firstElementChild,"on"),v(this,"on");u=this}function B(a,b,c,d){var f,e,g,h,l,k;f=document.createElement("div");e=document.createElement("button");g=document.createElement("div");h=document.createElement("label");l=document.createElement("button");k=document.createElement("button");
f.className="item";e.className="chk";h.className="label elps";k.className="btn link";l.className="btn del";f.setAttribute("data-domain",a);f.setAttribute("data-count",b);d&&(e.setAttribute("on",!0),f.setAttribute("on",!0));h.textContent=a+(c?" ("+b+")":"");e.appendChild(g);f.appendChild(e);f.appendChild(h);f.appendChild(l);f.appendChild(k);l.addEventListener("click",I,!1);k.addEventListener("click",H,!1);f.addEventListener("click",J,!1);return f}function y(a,b,c,d){a=h("list"+a);for(var f,e=document.createDocumentFragment(),
g=0;f=b[g];g+=2)f=B(f,b[g+1],c,d),e.appendChild(f);a.appendChild(e)}function A(a,b,c){for(var d=h("list"+b),f,e,g,n=0,l=0,k;k=c[l];l++){g=!0;f=k.getAttribute("data-domain");for(var m=0,p;p=d.children[m];m++)if(e=p.getAttribute("data-domain"),f==e){g=!1;break}else if(f<e){g=parseInt(k.getAttribute("data-count"));n+=g;e=k.firstElementChild.nextElementSibling;e.textContent=0==b?f+" ("+g+")":f;d.insertBefore(k,p);g=!1;break}g&&(g=parseInt(k.getAttribute("data-count")),n+=g,e=k.firstElementChild.nextElementSibling,
e.textContent=0==b?f+" ("+g+")":f,d.appendChild(k))}0<n&&(r(a,-n),r(b,n))}function G(a){for(var b,c=0;2>c;c++)if(a=this.getAttribute("data-d"+c)){a:{for(var d,f=a,e=h("list0").children,g=0;b=e[g];g++)if(d=b.getAttribute("data-domain"),d==f)break a;b=0}b=b?b.parentNode.removeChild(b):B(a,0,0,1);A(0,1,[b])}t()}function m(a){h("shade").className=a?"dbk":"nvw"}function h(a){return document.getElementById(a)}var u=-1;if("chrome"in window){var p=Object.getOwnPropertyDescriptor(chrome,"management");if(p){p.value=
{};p.configurable=!1;p.writable=!1;try{Object.defineProperty(chrome,"management",p)}catch(a){}}}window.addEventListener("DOMContentLoaded",function(){chrome.runtime.sendMessage(JSON.stringify({id:2}),C)},!1)})();
